syssetting_index:
    path:     /
    defaults: { _controller: "CustomAdminBundle:SystemSetting:index" }
    methods:  GET

syssetting_show:
    path:     /{id}/show
    defaults: { _controller: "CustomAdminBundle:SystemSetting:show" }
    methods:  GET

syssetting_new:
    path:     /new
    defaults: { _controller: "CustomAdminBundle:SystemSetting:new" }
    methods:  [GET, POST]

syssetting_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomAdminBundle:SystemSetting:edit" }
    methods:  [GET, POST]

syssetting_delete:
    path:     /{id}/delete
    defaults: { _controller: "CustomAdminBundle:SystemSetting:delete" }
    methods:  DELETE
